require Pod::Executable.execute_command('node', ['-e',
  "process.stdout.write(require('path').dirname(require.resolve('react-native/package.json')))"
]).strip + '/scripts/react_native_pods.rb'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'OTADemo' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # OTA SDK native module
  pod 'OTAModule', :path => '../../packages/sdk/ios'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
