-- ============================================================
-- OTA Platform — Storage Bucket & Policies
-- Migration: 20260609000004_ota_storage
-- Creates the private `ota` bucket and scoped storage RLS.
-- ============================================================

-- ── Create the private OTA bucket ────────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'ota',
  'ota',
  FALSE,  -- private — all access via signed URLs
  524288000,  -- 500 MB per file
  ARRAY[
    'application/zip',
    'application/octet-stream',
    'application/json',
    'text/javascript',
    'application/javascript',
    'image/png',
    'image/jpeg',
    'image/gif',
    'image/webp',
    'font/ttf',
    'font/otf',
    'font/woff',
    'font/woff2'
  ]
)
ON CONFLICT (id) DO NOTHING;

-- ── Storage path convention ───────────────────────────────────
-- ota/{app_slug}/{channel}/{platform}/{bundle_id}/bundle.zip
-- ota/{app_slug}/{channel}/{platform}/{bundle_id}/manifest.json
-- ota/{app_slug}/{channel}/{platform}/{bundle_id}/assets/{filename}
--
-- Signed URLs are minted by the check-update Edge Function (5-min TTL).
-- The CLI uploads via authenticated Supabase client using the user's JWT.
-- Devices NEVER upload — they only download via signed URLs.

-- ── Helper: extract app_slug from storage path ───────────────
-- Path format: ota/{slug}/{channel}/{platform}/{bundle_id}/...
-- split_part(name, '/', N) where N is 1-indexed
-- storage.objects.name does NOT include the bucket prefix.

-- ── Storage RLS ───────────────────────────────────────────────
-- Lookup: resolve slug → application_id for policy checks.
CREATE OR REPLACE FUNCTION public.ota_app_id_from_path(object_name TEXT)
RETURNS UUID LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT id FROM public.applications
  WHERE slug = split_part(object_name, '/', 1)
  LIMIT 1;
$$;

-- Operators (developer+) can upload bundles via the CLI / dashboard.
DROP POLICY IF EXISTS "ota: authenticated developers can upload" ON storage.objects;
CREATE POLICY "ota: authenticated developers can upload"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'ota'
    AND public.ota_is_app_member(
      public.ota_app_id_from_path(name),
      'developer'
    )
  );

-- Operators (viewer+) can download / list objects in their apps.
DROP POLICY IF EXISTS "ota: authenticated members can read" ON storage.objects;
CREATE POLICY "ota: authenticated members can read"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'ota'
    AND public.ota_is_app_member(
      public.ota_app_id_from_path(name),
      'viewer'
    )
  );

-- Operators (developer+) can update/replace objects.
DROP POLICY IF EXISTS "ota: authenticated developers can update" ON storage.objects;
CREATE POLICY "ota: authenticated developers can update"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'ota'
    AND public.ota_is_app_member(
      public.ota_app_id_from_path(name),
      'developer'
    )
  )
  WITH CHECK (
    bucket_id = 'ota'
    AND public.ota_is_app_member(
      public.ota_app_id_from_path(name),
      'developer'
    )
  );

-- Admins can delete objects.
DROP POLICY IF EXISTS "ota: authenticated admins can delete" ON storage.objects;
CREATE POLICY "ota: authenticated admins can delete"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'ota'
    AND public.ota_is_app_member(
      public.ota_app_id_from_path(name),
      'admin'
    )
  );

-- NOTE: Devices (anon / service role) access bundles exclusively via
-- short-lived signed URLs generated by the check-update Edge Function.
-- The `anon` role has NO storage policies — no direct device access.
-- The `service_role` bypasses RLS and can sign URLs for any path.
